name: Rachael Minto
favicon: null
layout_spectrum: 0.557352347066626
typography_spectrum: 0.5801816172897816
title: Rachael Minto
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#201841'
    - '#f5e2dc'
    - '#775e64'
    - '#b51329'
    - '#dd5e81'
  brandStrength: 0.5625
  lightness: 0.34850944788195193
  saturation: 0.25
  rhythmicContrast: 0.4619268497917801
purpose: []
