name: Rachael Minto
favicon: null
layout_spectrum: 0.557352347066626
typography_spectrum: 0.5801816172897816
title: Rachael Minto
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5959247187711298
  lightness: 0.34850944788195193
  saturation: 0.22412797063589096
  rhythmicContrast: 0.4619268497917801
purpose: []
